[workspace]
resolver = "2"
members = [
    "contracts/enrollment",
    "contracts/certificate",
    "contracts/completion",
    "contracts/verification",
    "contracts/reward",
]

[workspace.dependencies]
soroban-sdk = "22.0.0"

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
codegen-units = 1
lto = true
panic = "abort"
